// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2yJjFmto0Hlf6PvcD9VSKr8RYgle8o2M',
    appId: '1:1007313059054:web:78b26f7fc04e63fbaac7ff',
    messagingSenderId: '1007313059054',
    projectId: 'bookstore-rel',
    authDomain: 'bookstore-rel.firebaseapp.com',
    storageBucket: 'bookstore-rel.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh4ApbrMAc3oxXRd47m3MiFTLjTyd6VkE',
    appId: '1:1007313059054:android:6a6fe74b82e58276aac7ff',
    messagingSenderId: '1007313059054',
    projectId: 'bookstore-rel',
    storageBucket: 'bookstore-rel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSrHI2wLq8M6Su0H55zU6l0lMaIgO-FaM',
    appId: '1:1007313059054:ios:ad859c8891e6e8eeaac7ff',
    messagingSenderId: '1007313059054',
    projectId: 'bookstore-rel',
    storageBucket: 'bookstore-rel.appspot.com',
    iosClientId: '1007313059054-0h9cubusrn5juv9e1beq035l5pqsv0ar.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSrHI2wLq8M6Su0H55zU6l0lMaIgO-FaM',
    appId: '1:1007313059054:ios:ad859c8891e6e8eeaac7ff',
    messagingSenderId: '1007313059054',
    projectId: 'bookstore-rel',
    storageBucket: 'bookstore-rel.appspot.com',
    iosClientId: '1007313059054-0h9cubusrn5juv9e1beq035l5pqsv0ar.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookstore',
  );
}
